/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abmProfesores;

import dao.Dao;
import java.util.Map;
import jdk.nashorn.internal.runtime.regexp.joni.Config;

/**
 *
 * @author nestor
 */
public class datosConexionBDDialog extends javax.swing.JDialog {

    /**
     * Creates new form datosConexionBDDialog
     */
    public datosConexionBDDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textIp = new javax.swing.JLabel();
        textfielIp = new javax.swing.JTextField();
        textfieldPuerto = new javax.swing.JTextField();
        buttonAceptar = new javax.swing.JButton();
        textfieldDBName = new javax.swing.JTextField();
        textfieldPassword = new javax.swing.JPasswordField();
        textPort = new javax.swing.JLabel();
        textBDName = new javax.swing.JLabel();
        textPassworld = new javax.swing.JLabel();
        textUser = new javax.swing.JLabel();
        textfieldUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textIp.setText("IP");

        textfielIp.setText("jTextField1");

        textfieldPuerto.setText("jTextField2");

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });

        textfieldDBName.setText("jTextField3");

        textfieldPassword.setText("jPasswordField1");

        textPort.setText("Port");

        textBDName.setText("BD Name");

        textPassworld.setText("PassWord");

        textUser.setText("User");

        textfieldUser.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfielIp)
                            .addComponent(textIp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldPuerto)
                            .addComponent(textPort))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBDName)
                            .addComponent(textfieldDBName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textUser)
                            .addComponent(textfieldUser, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPassworld)
                            .addComponent(textfieldPassword))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIp)
                    .addComponent(textPort)
                    .addComponent(textBDName)
                    .addComponent(textPassworld)
                    .addComponent(textUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfielIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(buttonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
        
        ActualizarVariables();
        
        if(User.isEmpty() || textfielIp.getText().isEmpty() || textfieldPuerto.getText().isEmpty()|| textfieldDBName.getText().isEmpty())
        {  
            conectar = false;
            setVisible(false);
        }
        
        setVisible(false);
        conectar = true;
    }//GEN-LAST:event_buttonAceptarActionPerformed

    private void ActualizarVariables() {
        // TODO add your handling code here:
        User = textfieldUser.getText();
        Pass = textfieldPassword.getSelectedText();
        SetStringBDCon(textfielIp.getText(), textfieldPuerto.getText(),textfieldDBName.getText());
    }
    public String GetUser ()
    {
        return User;
    }
    
    public String GetPass ()
    {
        return Pass;
    }
    
    public String GetStringBDCon()
    {
        return StringConBD;
    }
    
    public void SetStringBDCon(String ip, String port,String bdName)
    {
        StringConBD = "jdbc:mysql://"+ip+":"+port+"/"+bdName+"?useTimezone=true&serverTimezone=GMT-3";
    }
    
    public boolean MostrarDatosDB() 
    {       
        IniciarDatos();
        setVisible(true);
        return conectar;
    }
    public void IniciarDatos ()
    {
        textfielIp.setText("127.0.0.1");
        textfieldPuerto.setText("3306");
        textfieldDBName.setText("universidad");
        textfieldUser.setText("root");
        textfieldPassword.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datosConexionBDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datosConexionBDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datosConexionBDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datosConexionBDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                datosConexionBDDialog dialog = new datosConexionBDDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private boolean conectar = false ;
    private String User;
    private String Pass;
    private String StringConBD;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JLabel textBDName;
    private javax.swing.JLabel textIp;
    private javax.swing.JLabel textPassworld;
    private javax.swing.JLabel textPort;
    private javax.swing.JLabel textUser;
    private javax.swing.JTextField textfielIp;
    private javax.swing.JTextField textfieldDBName;
    private javax.swing.JPasswordField textfieldPassword;
    private javax.swing.JTextField textfieldPuerto;
    private javax.swing.JTextField textfieldUser;
    // End of variables declaration//GEN-END:variables
}
